#!/bin/bash
#
# configure-network.sh - Network configuration for Proxmox VE
#
# This script configures network interfaces for Proxmox, including
# bridge setup for VMs and static IP configuration.

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "${GREEN}[NET]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[NET]${NC} $1"; }
log_error() { echo -e "${RED}[NET]${NC} $1"; }

# Get current network info
get_primary_interface() {
    ip route get 1 | awk '{print $5; exit}'
}

get_primary_ip() {
    ip route get 1 | awk '{print $7; exit}'
}

get_gateway() {
    ip route | grep default | awk '{print $3}'
}

get_netmask() {
    local iface=$(get_primary_interface)
    ip -o -f inet addr show "$iface" | awk '{print $4}' | cut -d'/' -f2
}

get_dns_servers() {
    grep "^nameserver" /etc/resolv.conf | awk '{print $2}' | tr '\n' ' '
}

show_current_config() {
    echo ""
    log_info "Current Network Configuration:"
    echo "  Interface: $(get_primary_interface)"
    echo "  IP Address: $(get_primary_ip)"
    echo "  Netmask: /$(get_netmask)"
    echo "  Gateway: $(get_gateway)"
    echo "  DNS: $(get_dns_servers)"
    echo ""
}

configure_static_ip() {
    local ip="$1"
    local netmask="$2"
    local gateway="$3"
    local dns="${4:-8.8.8.8 8.8.4.4}"
    local iface=$(get_primary_interface)

    log_info "Configuring static IP: $ip/$netmask"

    # Backup current config
    cp /etc/network/interfaces /etc/network/interfaces.backup.$(date +%Y%m%d%H%M%S)

    cat > /etc/network/interfaces << EOF
auto lo
iface lo inet loopback

auto ${iface}
iface ${iface} inet static
    address ${ip}/${netmask}
    gateway ${gateway}
EOF

    # Configure DNS
    cat > /etc/resolv.conf << EOF
# Generated by configure-network.sh
$(for server in $dns; do echo "nameserver $server"; done)
EOF

    log_info "Network configuration updated"
    log_warn "Run 'systemctl restart networking' or reboot to apply"
}

configure_bridge() {
    local bridge_name="${1:-vmbr0}"
    local iface=$(get_primary_interface)
    local ip=$(get_primary_ip)
    local netmask=$(get_netmask)
    local gateway=$(get_gateway)

    log_info "Creating bridge $bridge_name on $iface"

    # Backup current config
    cp /etc/network/interfaces /etc/network/interfaces.backup.$(date +%Y%m%d%H%M%S)

    cat > /etc/network/interfaces << EOF
auto lo
iface lo inet loopback

iface ${iface} inet manual

auto ${bridge_name}
iface ${bridge_name} inet static
    address ${ip}/${netmask}
    gateway ${gateway}
    bridge-ports ${iface}
    bridge-stp off
    bridge-fd 0
EOF

    log_info "Bridge $bridge_name configured"
    log_warn "Run 'systemctl restart networking' or reboot to apply"
}

configure_vlan() {
    local vlan_id="$1"
    local ip="$2"
    local netmask="$3"
    local iface=$(get_primary_interface)

    log_info "Creating VLAN $vlan_id on $iface"

    cat >> /etc/network/interfaces << EOF

auto ${iface}.${vlan_id}
iface ${iface}.${vlan_id} inet static
    address ${ip}/${netmask}
    vlan-raw-device ${iface}
EOF

    log_info "VLAN ${iface}.${vlan_id} configured"
}

show_help() {
    cat << 'EOF'
Network Configuration Script for Proxmox VE

Usage: ./configure-network.sh <command> [options]

Commands:
  show                          Show current network configuration
  static <ip> <mask> <gw> [dns] Configure static IP
  bridge [name]                 Create VM bridge (default: vmbr0)
  vlan <id> <ip> <mask>         Create VLAN interface

Examples:
  ./configure-network.sh show
  ./configure-network.sh static 192.168.1.100 24 192.168.1.1
  ./configure-network.sh static 192.168.1.100 24 192.168.1.1 "8.8.8.8 1.1.1.1"
  ./configure-network.sh bridge vmbr0
  ./configure-network.sh vlan 100 10.0.100.1 24
EOF
}

main() {
    if [[ $# -lt 1 ]]; then
        show_help
        exit 1
    fi

    local command="$1"
    shift

    case $command in
        show)
            show_current_config
            ;;
        static)
            if [[ $# -lt 3 ]]; then
                log_error "Usage: $0 static <ip> <netmask> <gateway> [dns]"
                exit 1
            fi
            configure_static_ip "$@"
            ;;
        bridge)
            configure_bridge "${1:-vmbr0}"
            ;;
        vlan)
            if [[ $# -lt 3 ]]; then
                log_error "Usage: $0 vlan <id> <ip> <netmask>"
                exit 1
            fi
            configure_vlan "$@"
            ;;
        -h|--help|help)
            show_help
            ;;
        *)
            log_error "Unknown command: $command"
            show_help
            exit 1
            ;;
    esac
}

main "$@"
